### ISSUE TITLE
Empty EventArgs

### ISSUE THREAD

**Issue by purplS1** [moritzuehling/demostatistics-generator#2]
Why are the EventArgs for half the Events just empty classes?

I am trying to recode the demoinfo project into Java and I am confused about some of the EventArgs that are just empty.

**Comment by moritzuehling** [comment]
Empty EventArgs can still be called - they just don't bring any information with them. For example [MatchStarted](https://github.com/StatsHelix/demoinfo/blob/3d28ea917c3d44d987b98bb8f976f1a3fcc19821/DemoInfo/Events.cs#L24) gives information that the match-started event has been emitted. However, the game doesn't give any information, so we pass along that there wasn't any information.
