### ISSUE TITLE
Method or operation is not implemented

### ISSUE THREAD

**Issue by Patryk-Szylin** [moritzuehling/demostatistics-generator#3]
Tried to use this tool but every time I try I get **"The method or operation is not implemented"**.

Now I don't know whether this is a problem related to a demo I [downloaded ](https://www.hltv.org/matches/2336310/evil-geniuses-vs-grayhound-dreamhack-masters-malm-2019) where an unhandled event in the game occurs or whether it is that I do not implement certain method. I subscribed to all events available in the parser to no success.

**UPDATE**
Can confirm this is an issue with outdated tool (expected as the last update was almost 5 years ago). [Downloaded this](https://www.hltv.org/matches/2294625/virtuspro-vs-keyd-esl-one-katowice-2015) demo and the tool worked fine

**Comment by moritzuehling** [comment]
Whoops, yeah. Consider using this: https://csgo-demos-manager.com/

Based on our old code, but updated

**Comment by AskDrax** [comment]
Can confirm using 'demoinfo' from https://github.com/akiver/CSGO-Demos-Manager works.

What I did was remove the DemoInfo 1.2.0 package from dependencies, then copy just 'demoinfo' from the CSGO-Demos-Manager repo into my solution folder and then in VS add existing project -> select the DemoInfo.csproj.

No other changes and it seems to be working. (It *does* take forever to parse if I do a debug build, but select Release and it seems to parse a 5v5 demo in 2-5 seconds or so)

**Comment by moritzuehling** [comment]
Yeah, the debug-build allows for easier inspection of the data, and has a different underlying structure. It's faster mostly because of that.

(In CS:GO you have to parse bit-by-bit, and you can either do a naive slow implementation, or a quick complicated one)
