### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by ShaddollAsu** [moritzuehling/demostatistics-generator#4]
I'm new to c-sharp.
I got err at 

> StatisticsGenerator/Program.cs
> parser.ParseToEnd();

how to resolve it?

**Comment by Mad-Kingu** [comment]
I also encounter with this error, you should check this issue, they did not solve but create a workaround for it. https://github.com/EHVAG/demostatistics-generator/issues/3

**Comment by ShaddollAsu** [comment]
> I also encounter with this error, you should check this issue, they did not solve but create a workaround for it. #3

thx
